bin/config.js, bin/publish.js, config/tanstack.config.js, docs/overview.md, package.json, pnpm-lock.yaml, src/index.d.ts, src/index.js, src/publish.d.ts, src/publish.js, src/types.d.ts
=> CLI Publish Command & Scaffolding

bin/config.js, tsconfig.json
Type checking isn't enabled yet (will do now), and it wasn't getting IDE hints since tsconfig didn't include the bin directory.
=> fix: Fix publish import for CLI

package.json, pnpm-lock.yaml
Hopefully fixes `Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vite-plugin-externalize-deps'` on trying to use `tanstackBuildConfig`
=> fix: Mark `vite-plugin-dts` and `vite-plugin-externalize-deps` as dependencies

docs/build.md
Specifically instructs users to put `tanstackBuildConfig` after their custom config, to ensure it will override where it needs to.
=> docs: Tweak Vite build instructions

.eslintrc.cjs, bin/config.js, package.json, src/publish/index.js
When I added more ESLint rules, nothing happened. Seems like we forgot to tell eslint to include `.js` files! This PR corrects ESLint to ensure it runs on all the source files, and adds some new rules from `eslint-plugin-import` to keep imports sorted nicely (config from the query repo). I've also fixed a `no-shadow` rule in the publish function.
=> fix: Run ESLint on JS files, sort imports

integrations/react/tests/build.test.ts, integrations/vue/tests/build.test.ts
This gets an array of all files and folders in the `dist` and `snap` directories, and ensures they match.
=> test: Ensure all integration dist files match

package.json, pnpm-lock.yaml, src/publish/index.js
Uses built-in fetch API in place of axios for the single request made by publish. Looks like it removes ~10 sub-dependencies that needed to be installed.
=> perf: Replace axios with fetch

src/publish/index.js
- Iterates over files in `/examples` directory and finds `package.json` files
- For each `package.json`, checks if an updated package is in dependencies
- If present, it sets the dependency to the new version
=> fix: Update example dependencies when publishing

src/publish/index.js
This caused `pnpm install --frozen-lockfile` to break. The underlying issue with Table's examples was actually that exact package versions were specified, rather than semantic ranges.
=> fix: Disable updating example dependencies

src/publish/index.js, src/publish/utils.js
- Moved helper functions (e.g. `updatePackageJson`) out of the main exported file
- Replaced some unnecessary template literals with regular strings
=> refactor: Split helper functions out of main export

src/publish/index.js
This script was copied from TanStack Query, and has a bug introduced in: https://github.com/TanStack/query/pull/6247
```
const tagParam = branchConfig.previousVersion ? `` : `--tag ${npmTag}`
```
When no tag is set, the [default](https://docs.npmjs.com/cli/v7/commands/npm-publish#tag) is `latest`, hence the v4 branch published as latest. This change would make it publish instead as `v4`.
=> fix: Incorrect npm tag for previous version release

integrations/react/snap/cjs/use-client.cjs, integrations/react/snap/cjs/use-client.cjs.map, integrations/react/snap/esm/use-client.js, integrations/react/snap/esm/use-client.js.map, nx.json, package.json, pnpm-lock.yaml, src/build/index.js
Keeps directives like `"use client"`.
TODO:
=> feat: Add rollup-plugin-preserve-directives

src/build/index.js
`afterBuild` provides a map which contains all the emitted declaration paths. This is simpler and probably faster than using `readdirSync`.
=> refactor: Simplify CJS type renaming

integrations/react/package.json, integrations/react/snap/cjs/index.cjs, integrations/react/snap/cjs/index.cjs.map, integrations/react/snap/cjs/index.d.cts, integrations/react/snap/esm/index.d.ts, integrations/react/snap/esm/index.js, integrations/react/snap/esm/index.js.map, integrations/react/src/index.ts, integrations/solid/package.json, integrations/solid/snap/cjs/index.d.cts, integrations/solid/snap/esm/index.d.ts, integrations/vanilla/package.json, integrations/vanilla/snap/cjs/index.d.cts, integrations/vanilla/snap/esm/index.d.ts, integrations/vue/package.json, package.json, pnpm-lock.yaml, src/build/index.js
Uses the following regex to add `.js` or `.cjs` extensions to declaration files:
```
content = content.replace(
/^import\s[\w{}*\s,]+from\s['"]\.\/[^.'"]+(?=['"];?$)/gm,
'$&.js',
)
content = content.replace(
/^export\s[\w{}*\s,]+from\s['"]\.\/[^.'"]+(?=['"];?$)/gm,
'$&.js',
)
```
Added `@arethetypeswrong/cli` to ensure all module resolutions pass.
=> feat: Add extension to relative imports/exports in declaration files

src/publish/index.js
PR #18 was reverted because it did not update the lockfile, which was very annoying for anyone submitting new PRs. This changes the logic to run `pnpm install` after modifying example versions, and pushing the new lockfile with the release commit.
=> feat: Update example dependencies when publishing

docs/build.md, integrations/react/vite.config.ts, integrations/solid/vite.config.ts, integrations/vanilla/vite.config.ts, integrations/vue/vite.config.ts
Recommend to use `./src/index.ts` instead of `src/index.ts`.
=> docs: Relative entry paths

src/build/index.d.ts, src/build/index.js
Still defaults to `dist`, but can be customised if necessary
=> feat: Add option to specify build output directory

src/build/index.d.ts, src/build/index.js
=> Allow additional externals to be included

src/build/index.d.ts, src/build/index.js
- `include` marks something as excluded
- `except` marks something as to be bundled (confusing I know)
- Renamed `externalInclude` to `bundledDeps` which is clearer IMO
=> chore: Fix `vite-plugin-externalize-deps` `except` field

.eslintrc.cjs, src/build/index.d.ts, src/build/index.js, src/publish/types.d.ts
Re-fixes #42 after my confusion around option naming 🤦 
New description:
```
/** Additional dependencies to externalize if not detected by `vite-plugin-externalize-deps` */
externalDeps?: Array<string | RegExp>
```
Note `bundledDeps` did not work (included `node_modules` in output), so it has been removed
=> fix: replace `bundledDeps` with `externalDeps`

package.json, pnpm-lock.yaml, src/build/index.d.ts, src/build/index.js, src/publish/index.d.ts
Allows Vite to automatically alias paths in tsconfig, meaning you don't need to double-up on the same config.
=> feat: Add `vite-tsconfig-paths` plugin

.github/workflows/ci.yml, .github/workflows/pr.yml, src/publish/index.js
Issue noticed in https://github.com/TanStack/router/pull/1564, where the `@tanstack/config` preinstall script was running (and failing) on CI.
For all the other tanstack projects, the preinstall script is in the root workspace package.json and is not published, so no problem occurs. For this project, the root workspace package.json is the published one, and therefore gets run by anyone installing the package.
This PR clears the scripts section of packages just before the publish step. The changes are not committed (unlike the versioning changes).
=> fix(publish): Remove scripts section

src/publish/index.js
I fall for this async problem every time...
#85 did not remove the scripts section. By replacing the async `forEach` loops with `for...of` loops, execution order should be fixed (🤞)
=> fix(publish): Replace forEach loop with for/of

src/publish/index.js
Since `data.items` can be empty, need to check if `data.items[0]` exists before usage.
=> fix(publish): Correct types for github search API

package.json, pnpm-lock.yaml, src/publish/index.js
Within `src/publish` the largest dependency is [`luxon`](https://moment.github.io/luxon/#/). 
The `luxon` package is only used once to format the date of the change-log Markdown. 
The native [`Intl.DateTimeFormat() constructor`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat) can be used instead, which helps eliminate a dependency.
=> refactor(publish): Remove `luxon` dependency

src/build/index.js
TS 5.5 no longer supports strings passed to `vite-plugin-dts`. This was nicer for readability.
Fixes https://github.com/TanStack/router/pull/1727
Closes #81
=> fix: TS 5.5 compatibility

packages/config/src/publish/index.js
This error occurred on a TanStack Router workflow:
```
if (data.items.length && data.items[0]) {
^
TypeError: Cannot read properties of undefined (reading 'length')
```
This PR requires changes the API data type from `{items: Array<{login: string}>}` to `unknown`, and uses conditionals to narrow the type
=> fix(publish): better GitHub API type-safety

packages/config/src/typedoc/index.js, packages/config/src/typedoc/typedoc-custom-settings.js
As discussed on Discord
Now lowercase file names don't override each other :)
=> fix(typedoc): Disable flattenOutputFiles

packages/config/src/typedoc/index.d.ts, packages/config/src/typedoc/index.js
Alternative to #150 
Means that docs for older versions (e.g. Query v4) can still generate links to that version's source
=> feat(typedoc): allow customising branch in GitHub link

packages/config/src/vite/index.js, pnpm-lock.yaml
In #2342, noticed that type errors during build fail silently (also missed by tsc).
This PR adds the `afterDiagnostic` hook to throw a non-zero exit code if there are any "diagnostics" (type errors).
=> fix(vite): return non-zero exit code for type declaration errors

.github/renovate.json, packages/config/package.json, pnpm-lock.yaml
Fixes build-only type issues in TanStack Router repo. For example, `@tanstack/start-vite-plugin`:
vite-plugin-dts 4.1.0:
```
vite v5.4.5 building for production...
src/index.ts:3:15 - error TS2305: Module '"../../../node_modules/vite/index.cjs"' has no exported member 'Plugin'.
3 import type { Plugin } from 'vite'
~~~~~~
src/index.ts:17:22 - error TS7006: Parameter 'config' implicitly has an 'any' type.
17     configResolved: (config) => {
~~~~~~
src/index.ts:20:15 - error TS7006: Parameter 'code' implicitly has an 'any' type.
20     transform(code, id) {
~~~~
src/index.ts:20:21 - error TS7006: Parameter 'id' implicitly has an 'any' type.
20     transform(code, id) {
~~
Please fix the above type errors
 ELIFECYCLE  Command failed with exit code 1.
```
vite-plugin-dts 4.0.3:
```
vite …
```
=> fix(vite): downgrade vite-plugin-dts

packages/config/src/eslint/index.js
otherwise eslint might trip over such temp file like this:
Error: ENOENT: no such file or directory, open '/home/workflows/workspace/packages/react-router/vite.config.ts.timestamp-1727808513722-641dfc845ba89.mjs'
=> fix: ignore temporary vite config files

packages/config/package.json, packages/config/src/publish/index.js, pnpm-lock.yaml
This PR addresses feedback sent here:
https://github.com/asamuzaK/cssColor/pull/41#issuecomment-2587015577
By removing an old dependency that we didn't really need.
=> fix: remove vulnerable dependency

packages/config/src/vite/index.js
I noticed that `../../test` wasn't being transformed in the `.cjs` or `.js` import changer. This fixes that
=> fix: updates imports that are more than one parent high

integrations/vue/snap/cjs/components/HelloWorld.vue.d.cts, integrations/vue/snap/esm/components/HelloWorld.vue.d.ts, pnpm-lock.yaml, pnpm-workspace.yaml
Cause: https://github.com/qmhc/vite-plugin-dts/compare/v4.2.3...v4.2.4
vite-plugin-dts v4.2.4 and above will replace imports from workspace packages with their tsconfig path aliases. This behaviour is not portable.
Fixes #208
=> fix(vite): downgrade vite-plugin-dts to v4.2.3

.changeset/giant-wombats-sneeze.md, packages/publish-config/src/index.js
I'm surprised we haven't run into this problem before. Old releases don't currently work, as npm won't allow tags that match semver:
`npm error Tag name must not be a valid SemVer range: v4`
This PR marks old branches with the tag `previous`. This is similar to the strategy used by Vite: https://www.npmjs.com/package/vite?activeTab=versions
=> fix(publish): use 'previous' npm tag for old releases

.changeset/afraid-states-reply.md, packages/eslint-config/package.json, packages/eslint-config/src/index.js, pnpm-lock.yaml, pnpm-workspace.yaml
- [@stylistic/eslint-plugin-js](https://eslint.style/packages/js) is now deprecated in favour of unified [@stylistic/eslint-plugin](https://eslint.style/packages/default)
- the PR makes the transition for the same
=> fix: @stylistic/eslint-plugin-js to @stylistic/eslint-plugin

.changeset/eleven-clowns-create.md, packages/publish-config/src/index.js
In @tanstack/angular-query I need to run a `prepack` lifecycle script.
Currently, the publish script removes all scripts before publishing.
=> fix(publish): do not remove package scripts

docs/config.json
https://tanstack.com/config/latest/docs/nx returns a 404. After investigating, I realized that it was most likely due to the nx doc being updated and then expanded into the CI/CD doc. This is a very small update to instead point to the newer CI/CD doc, of which contains an nx section.
=> Update sidebar link to fix 404

.github/setup/action.yml
Turns out https://github.com/actions/setup-node/releases/tag/v5.0.0 enabled caching by default. So workflows have been double-downloading and double-uploading caches. This returns it to a normal amount of cache :)
=> ci: disable caching in `actions/setup-node`
