.github/workflows/ci.yml
.github/workflows/pr.yml
nx.json
package.json
pnpm-lock.yaml

`pnpm test:pr` was missing, causing GitHub CI to fail. This adds Nx to parallelise and order any scripts we do add.

fix: Functional GitHub workflow

---

src/publish.js

Per our most recent CI run, this should not work. This PR fixes this.

fix: fixes 0.0.1 release issues

---

tsconfig.json

- Disabled allowUnreachableCode and allowUnusedLabels
- Enabled noUnusedParameters
- Removed noImplicitAny and strictNullChecks (enabled by strict)
- Removed baseUrl

chore: Add missing tsconfig properties from query repo

---

src/publish/index.js

Previously, if a manual tag was set, the entire changelog list is overriden by `Manual Release: ${tag}`. However, in many cases, there is an actual changelog to display.
Now, the manual release indication is on the top line of the notes as `(Manual Release)`, and if there really are no notes, the changelog shows `- None`.

fix: Display changelog for manual releases

---

integrations/react/snap/cjs/index.d.cts
integrations/react/snap/esm/index.d.ts
integrations/react/src/index.ts
src/build/index.js

Replaced
`/^import\s[\w{}*\s,]+from\s['"]\.\/[^.'"]+(?=['"];?$)/gm` and `/^export\s[\w{}*\s,]+from\s['"]\.\/[^.'"]+(?=['"];?$)/gm`
with
`/^(im|ex)port\s[\w{}*\s,]+from\s['"]\.\/[^.'"]+(?=['"];?$)/gm`

refactor: Merge import and export regex

---

nx.json

https://nx.dev/ci/recipes/security/access-tokens

ci: Add read-only Nx cloud token

---

.github/workflows/evergreen.yml

https://github.blog/2024-01-25-do-you-know-if-all-your-repositories-have-up-to-date-dependencies/

ci: Trial github/evergreen action

---

src/publish/index.js

Things executed in the wrong order in #84

fix(publish): Remove async/await from publish logic

---

docs/overview.md

You can go here in the docs and see the link is not currently working: https://tanstack.com/config/latest/docs/overview

Fix relative links in markdown

---

package.json
pnpm-lock.yaml
src/eslint/index.d.ts
src/eslint/index.js

Simplifies usage with vue and svelte

fix: Add extraFileExtensions

---

.github/workflows/preview.yml

Made possible by https://github.com/stackblitz-labs/pkg.pr.new

ci: Add preview workflow

---

.github/workflows/autofix.yml
.github/workflows/ci.yml
.github/workflows/pr.yml
tanstack.config.js

- Add autofix.ci
- Use local reference to setup action

ci: Update GitHub workflows

---

.github/workflows/autofix.yml
docs/ci-cd.md
docs/overview.md
docs/package-structure.md
tanstack.config.js

ci: Enable autofix on push to release branch

---

packages/config/src/eslint/index.js
packages/config/src/eslint/typescript.js

Fixes #115.
I can send a PR after this one that applies the suggestion in #114 to base on the recommended presets.

fix: switch 'ts/' prefix to '@typescript-eslint/'

---

packages/config/src/vite/index.js

required for https://github.com/TanStack/router/issues/2190

fix: correctly add file extensions for dynamic imports

---

packages/config/src/vite/index.js

required for https://github.com/TanStack/router/issues/2223

fix: correctly add file extensions for relative imports

---

package.json
packages/config/package.json
packages/config/src/eslint/typescript.js
pnpm-lock.yaml

ESLint plugins in other projects should all be compatible now 🤞

feat(eslint): upgrade to eslint v9, typescript-eslint v8

---

integrations/vue/snap/cjs/components/HelloWorld.vue.d.cts
integrations/vue/snap/esm/App.vue2.js
integrations/vue/snap/esm/components/HelloWorld.vue.d.ts
integrations/vue/snap/esm/components/HelloWorld.vue2.js
packages/config/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

Previous issue with upgrading from 4.0.3 seems to have been resolved

chore(deps): bump vite-plugin-dts

---

package.json

See https://github.com/TanStack/virtual/pull/953

ci: fix changeset version script

---

.changeset/clean-ways-speak.md
.changeset/open-masks-create.md
.github/renovate.json
pnpm-lock.yaml
pnpm-workspace.yaml

Frequent breaking changes which often need manual upgrades to this config.

fix: pin typedoc deps

---

.github/workflows/autofix.yml
.github/workflows/pr.yml
docs/overview.md
docs/package-structure.md
package.json
pnpm-lock.yaml
pnpm-workspace.yaml
scripts/verify-links.ts
tsconfig.json

- Takes code from tanstack query to verify doc links

ci: add doc link verification

---

.changeset/grumpy-plants-cross.md
eslint.config.js
package.json
packages/config/package.json
packages/eslint-config/eslint.config.js
packages/eslint-config/package.json
packages/publish-config/eslint.config.js
packages/publish-config/package.json
packages/typedoc-config/eslint.config.js
packages/typedoc-config/package.json
packages/vite-config/eslint.config.js
packages/vite-config/package.json
pnpm-lock.yaml
pnpm-workspace.yaml
tsconfig.json

- Updates dependencies used by these packages
- Adds eslint [concurrency](https://github.com/eslint/eslint/pull/19794)
- Fixes eslint modular config

chore: update dependencies

---

.github/setup/action.yml

See here: https://github.com/danielroe/provenance-action

ci: add `danielroe/provenance-action`

---

pnpm-workspace.yaml

ci: remove `minimumReleaseAge`
